---
title: "Project Proposal"
output: github_document
authors: "Team tidyverse: Hongyi Yu; Jeffrey Emmons; Katie Hansen; Yuqing Yang"
---


## Introduction

We will be investigating the relationship between Daylight Saving Time
and road safety in the United Kingdom using the ["Spring Forward, Don't Fall Back: The Effect of Daylight Saving Time on Road Safety"](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/UVUXDR) dataset
(Department for Transport, 2017b). We will look at how factors such as
the time of year, the amount of light during the day, and the geographic
region might affect the number of accidents that occur. We will also
analyze the impact of driver age and the long-term consequences of Daylight Saving time on road
safety in different geographic regions.


## Data Description 

The dataset includes detailed information on the date of year from 1996 to 2017, the number of car accidents in a given hour, and the weather conditions during that time. For our investigation, we will focus on the following variables from the dataset: mlong, mlat, date, all_accid, u25_accid, o25u45_accid, o45u65_accid, o65_accid, year, doy (day of the year), dow (day of the week), longlat, dark (proportion of hours that is dark), darkh (number of dark hours on that day). mlong and mlat indicate the longitude and latitude of the center of the region where the accident occurred. The number of accidents are separated by the age of the driver (under 25, 26-45, 46-65, and over 65). Longlat is the identifier for the region in which the accident occurred, where in total 265 regions.


## Research Questions

- How does Daylight Saving Time affect road safety?
- Has the effect of Daylight Saving Time on road safety changed throughout the decades? 
- Does the age of the driver affect the number of accidents due to Daylight Saving Time?
